/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// BackendInfoResponse
    /// </summary>
    [DataContract(Name = "BackendInfoResponse")]
    public partial class BackendInfoResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackendInfoResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BackendInfoResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BackendInfoResponse" /> class.
        /// </summary>
        /// <param name="varVersion">varVersion (required).</param>
        /// <param name="commit">commit (required).</param>
        /// <param name="currentTime">currentTime (required).</param>
        /// <param name="frontendUrl">frontendUrl (required).</param>
        /// <param name="shortLinkUrl">shortLinkUrl (required).</param>
        /// <param name="turnstileSiteKey">turnstileSiteKey (required).</param>
        /// <param name="oAuthProviders">oAuthProviders (required).</param>
        /// <param name="isUserAuthenticated">isUserAuthenticated (required).</param>
        public BackendInfoResponse(string varVersion = default, string commit = default, DateTime currentTime = default, string frontendUrl = default, string shortLinkUrl = default, string turnstileSiteKey = default, List<string> oAuthProviders = default, bool isUserAuthenticated = default)
        {
            // to ensure "varVersion" is required (not null)
            if (varVersion == null)
            {
                throw new ArgumentNullException("varVersion is a required property for BackendInfoResponse and cannot be null");
            }
            this.VarVersion = varVersion;
            // to ensure "commit" is required (not null)
            if (commit == null)
            {
                throw new ArgumentNullException("commit is a required property for BackendInfoResponse and cannot be null");
            }
            this.Commit = commit;
            this.CurrentTime = currentTime;
            // to ensure "frontendUrl" is required (not null)
            if (frontendUrl == null)
            {
                throw new ArgumentNullException("frontendUrl is a required property for BackendInfoResponse and cannot be null");
            }
            this.FrontendUrl = frontendUrl;
            // to ensure "shortLinkUrl" is required (not null)
            if (shortLinkUrl == null)
            {
                throw new ArgumentNullException("shortLinkUrl is a required property for BackendInfoResponse and cannot be null");
            }
            this.ShortLinkUrl = shortLinkUrl;
            // to ensure "turnstileSiteKey" is required (not null)
            if (turnstileSiteKey == null)
            {
                throw new ArgumentNullException("turnstileSiteKey is a required property for BackendInfoResponse and cannot be null");
            }
            this.TurnstileSiteKey = turnstileSiteKey;
            // to ensure "oAuthProviders" is required (not null)
            if (oAuthProviders == null)
            {
                throw new ArgumentNullException("oAuthProviders is a required property for BackendInfoResponse and cannot be null");
            }
            this.OAuthProviders = oAuthProviders;
            this.IsUserAuthenticated = isUserAuthenticated;
        }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = true)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets Commit
        /// </summary>
        [DataMember(Name = "commit", IsRequired = true, EmitDefaultValue = true)]
        public string Commit { get; set; }

        /// <summary>
        /// Gets or Sets CurrentTime
        /// </summary>
        [DataMember(Name = "currentTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CurrentTime { get; set; }

        /// <summary>
        /// Gets or Sets FrontendUrl
        /// </summary>
        [DataMember(Name = "frontendUrl", IsRequired = true, EmitDefaultValue = true)]
        public string FrontendUrl { get; set; }

        /// <summary>
        /// Gets or Sets ShortLinkUrl
        /// </summary>
        [DataMember(Name = "shortLinkUrl", IsRequired = true, EmitDefaultValue = true)]
        public string ShortLinkUrl { get; set; }

        /// <summary>
        /// Gets or Sets TurnstileSiteKey
        /// </summary>
        [DataMember(Name = "turnstileSiteKey", IsRequired = true, EmitDefaultValue = true)]
        public string TurnstileSiteKey { get; set; }

        /// <summary>
        /// Gets or Sets OAuthProviders
        /// </summary>
        [DataMember(Name = "oAuthProviders", IsRequired = true, EmitDefaultValue = true)]
        public List<string> OAuthProviders { get; set; }

        /// <summary>
        /// Gets or Sets IsUserAuthenticated
        /// </summary>
        [DataMember(Name = "isUserAuthenticated", IsRequired = true, EmitDefaultValue = true)]
        public bool IsUserAuthenticated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BackendInfoResponse {\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Commit: ").Append(Commit).Append("\n");
            sb.Append("  CurrentTime: ").Append(CurrentTime).Append("\n");
            sb.Append("  FrontendUrl: ").Append(FrontendUrl).Append("\n");
            sb.Append("  ShortLinkUrl: ").Append(ShortLinkUrl).Append("\n");
            sb.Append("  TurnstileSiteKey: ").Append(TurnstileSiteKey).Append("\n");
            sb.Append("  OAuthProviders: ").Append(OAuthProviders).Append("\n");
            sb.Append("  IsUserAuthenticated: ").Append(IsUserAuthenticated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
