/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// MinimalShocker
    /// </summary>
    [DataContract(Name = "MinimalShocker")]
    public partial class MinimalShocker : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public ShockerModelType Model { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MinimalShocker" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MinimalShocker() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MinimalShocker" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="rfId">rfId (required).</param>
        /// <param name="model">model (required).</param>
        public MinimalShocker(Guid id = default, int rfId = default, ShockerModelType model = default)
        {
            this.Id = id;
            this.RfId = rfId;
            this.Model = model;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets RfId
        /// </summary>
        [DataMember(Name = "rfId", IsRequired = true, EmitDefaultValue = true)]
        public int RfId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MinimalShocker {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RfId: ").Append(RfId).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
