/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// Defines PermissionType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PermissionType
    {
        /// <summary>
        /// Enum ShockersUse for value: shockers.use
        /// </summary>
        [EnumMember(Value = "shockers.use")]
        ShockersUse = 1,

        /// <summary>
        /// Enum ShockersEdit for value: shockers.edit
        /// </summary>
        [EnumMember(Value = "shockers.edit")]
        ShockersEdit = 2,

        /// <summary>
        /// Enum ShockersPause for value: shockers.pause
        /// </summary>
        [EnumMember(Value = "shockers.pause")]
        ShockersPause = 3,

        /// <summary>
        /// Enum DevicesEdit for value: devices.edit
        /// </summary>
        [EnumMember(Value = "devices.edit")]
        DevicesEdit = 4,

        /// <summary>
        /// Enum DevicesAuth for value: devices.auth
        /// </summary>
        [EnumMember(Value = "devices.auth")]
        DevicesAuth = 5
    }

}
