/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// ShockerPermissions
    /// </summary>
    [DataContract(Name = "ShockerPermissions")]
    public partial class ShockerPermissions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerPermissions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShockerPermissions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerPermissions" /> class.
        /// </summary>
        /// <param name="vibrate">vibrate (required).</param>
        /// <param name="sound">sound (required).</param>
        /// <param name="shock">shock (required).</param>
        /// <param name="live">live.</param>
        public ShockerPermissions(bool vibrate = default, bool sound = default, bool shock = default, bool live = default)
        {
            this.Vibrate = vibrate;
            this.Sound = sound;
            this.Shock = shock;
            this.Live = live;
        }

        /// <summary>
        /// Gets or Sets Vibrate
        /// </summary>
        [DataMember(Name = "vibrate", IsRequired = true, EmitDefaultValue = true)]
        public bool Vibrate { get; set; }

        /// <summary>
        /// Gets or Sets Sound
        /// </summary>
        [DataMember(Name = "sound", IsRequired = true, EmitDefaultValue = true)]
        public bool Sound { get; set; }

        /// <summary>
        /// Gets or Sets Shock
        /// </summary>
        [DataMember(Name = "shock", IsRequired = true, EmitDefaultValue = true)]
        public bool Shock { get; set; }

        /// <summary>
        /// Gets or Sets Live
        /// </summary>
        [DataMember(Name = "live", EmitDefaultValue = true)]
        public bool Live { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShockerPermissions {\n");
            sb.Append("  Vibrate: ").Append(Vibrate).Append("\n");
            sb.Append("  Sound: ").Append(Sound).Append("\n");
            sb.Append("  Shock: ").Append(Shock).Append("\n");
            sb.Append("  Live: ").Append(Live).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
