/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// Defines UsernameErrorType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UsernameErrorType
    {
        /// <summary>
        /// Enum TooShort for value: TooShort
        /// </summary>
        [EnumMember(Value = "TooShort")]
        TooShort = 1,

        /// <summary>
        /// Enum TooLong for value: TooLong
        /// </summary>
        [EnumMember(Value = "TooLong")]
        TooLong = 2,

        /// <summary>
        /// Enum StartOrEndWithWhitespace for value: StartOrEndWithWhitespace
        /// </summary>
        [EnumMember(Value = "StartOrEndWithWhitespace")]
        StartOrEndWithWhitespace = 3,

        /// <summary>
        /// Enum ResembleEmail for value: ResembleEmail
        /// </summary>
        [EnumMember(Value = "ResembleEmail")]
        ResembleEmail = 4,

        /// <summary>
        /// Enum ObnoxiousCharacters for value: ObnoxiousCharacters
        /// </summary>
        [EnumMember(Value = "ObnoxiousCharacters")]
        ObnoxiousCharacters = 5,

        /// <summary>
        /// Enum Blacklisted for value: Blacklisted
        /// </summary>
        [EnumMember(Value = "Blacklisted")]
        Blacklisted = 6
    }

}
