openapi: 3.0.4
info:
  title: OpenShock.API
  version: "2"
servers:
- url: https://api.openshock.app
- url: https://api.openshock.dev
tags:
- description: Shocker management
  name: Shockers
- description: Shocker share management
  name: User Shocker Shares
- description: Device management
  name: Hub Management
- description: For devices (ESP's)
  name: Hub Endpoints
- description: User account management
  name: Account
paths:
  /2/account/username/check:
    post:
      operationId: Account_CheckUsername
      summary: Check if a username is available
      tags:
      - Account
  /2/account/login:
    post:
      operationId: Account_LoginV2
      summary: Authenticate a user
      tags:
      - Account
  /2/account/password-reset:
    post:
      operationId: Account_PasswordResetInitiateV2
      summary: Initiate a password reset
      tags:
      - Account
  /2/account/reset-password:
    post:
      deprecated: true
      operationId: Account_PasswordResetInitiateV2Legacy
      summary: "Initiate a password reset. Deprecated: use POST /password-reset instead."
      tags:
      - Account
  /2/account/signup:
    post:
      operationId: Account_SignUpV2
      summary: Signs up a new user
      tags:
      - Account
  /2/device/assignLCG:
    get:
      operationId: Device_GetLiveControlGatewayV2
      security:
      - HubToken:
        - AuthenticationSchemes:HubToken
      summary: Gets the best suited LCG node for the client
      tags:
      - Hub Endpoints
  /2/devices:
    post:
      operationId: Devices_CreateDeviceV2
      security:
      - UserSessionCookie:
        - "AuthenticationSchemes:UserSessionCookie,ApiToken"
      - ApiToken:
        - "AuthenticationSchemes:UserSessionCookie,ApiToken"
      summary: Create a new device for the current user
      tags:
      - Hub Management
  /2/shockers/control:
    post:
      operationId: Shocker_SendControl
      security:
      - UserSessionCookie:
        - "AuthenticationSchemes:UserSessionCookie,ApiToken"
      - ApiToken:
        - "AuthenticationSchemes:UserSessionCookie,ApiToken"
      summary: Send a control message to shockers
      tags:
      - Shockers
  /2/shares/user/invites:
    post:
      operationId: UserShares_CreateShareInvite
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
  /2/shares/user:
    get:
      operationId: UserShares_GetSharesByUsers
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
  /2/shares/user/invites/outgoing:
    get:
      operationId: UserShares_GetOutgoingInvitesList
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
  /2/shares/user/invites/incoming:
    get:
      operationId: UserShares_GetIncomingInvitesList
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
  /2/shares/user/invites/outgoing/{inviteId}:
    delete:
      operationId: UserShares_DeleteOutgoingInvite
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
  /2/shares/user/invites/incoming/{inviteId}:
    delete:
      operationId: UserShares_DenyIncomingInvite
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
    post:
      operationId: UserShares_RedeemInvite
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      summary: Accept a share request and share the shockers with the current user.
      tags:
      - User Shocker Shares
  /2/shares/user/{userId}/shockers/pause:
    post:
      operationId: UserShares_BulkPauseUserShareShockers
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
  /2/shares/user/{userId}/shockers:
    delete:
      operationId: UserShares_BulkRemoveUserShareShockers
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      tags:
      - User Shocker Shares
    patch:
      operationId: UserShares_BulkUserShareShockersUpdate
      security:
      - UserSessionCookie:
        - AuthenticationSchemes:UserSessionCookie
      summary: Update user shares for a shocker
      tags:
      - User Shocker Shares
components:
  securitySchemes:
    UserSessionCookie:
      description: Enter user session cookie
      in: cookie
      name: openShockSession
      type: apiKey
    ApiToken:
      description: Enter API Token
      in: header
      name: OpenShockToken
      type: apiKey
    HubToken:
      description: Enter hub token
      in: header
      name: DeviceToken
      type: apiKey

