/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CShocker.GeneratedClients.OpenShockClientv1.Client;
using CShocker.GeneratedClients.OpenShockClientv1.Model;

namespace CShocker.GeneratedClients.OpenShockClientv1.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetaApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets online devices statistics
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>StatsResponseLegacyDataResponse</returns>
        StatsResponseLegacyDataResponse PublicGetOnlineDevicesStatistics();

        /// <summary>
        /// Gets online devices statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of StatsResponseLegacyDataResponse</returns>
        ApiResponse<StatsResponseLegacyDataResponse> PublicGetOnlineDevicesStatisticsWithHttpInfo();
        /// <summary>
        /// Gets the version of the OpenShock backend.
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>BackendInfoResponseLegacyDataResponse</returns>
        BackendInfoResponseLegacyDataResponse VersionGetBackendInfo();

        /// <summary>
        /// Gets the version of the OpenShock backend.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of BackendInfoResponseLegacyDataResponse</returns>
        ApiResponse<BackendInfoResponseLegacyDataResponse> VersionGetBackendInfoWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetaApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets online devices statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatsResponseLegacyDataResponse</returns>
        System.Threading.Tasks.Task<StatsResponseLegacyDataResponse> PublicGetOnlineDevicesStatisticsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets online devices statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatsResponseLegacyDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<StatsResponseLegacyDataResponse>> PublicGetOnlineDevicesStatisticsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Gets the version of the OpenShock backend.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BackendInfoResponseLegacyDataResponse</returns>
        System.Threading.Tasks.Task<BackendInfoResponseLegacyDataResponse> VersionGetBackendInfoAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the version of the OpenShock backend.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BackendInfoResponseLegacyDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BackendInfoResponseLegacyDataResponse>> VersionGetBackendInfoWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetaApi : IMetaApiSync, IMetaApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MetaApi : IDisposable, IMetaApi
    {
        private CShocker.GeneratedClients.OpenShockClientv1.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MetaApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MetaApi(string basePath)
        {
            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MetaApi(CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MetaApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MetaApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MetaApi(HttpClient client, CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MetaApi(CShocker.GeneratedClients.OpenShockClientv1.Client.ISynchronousClient client, CShocker.GeneratedClients.OpenShockClientv1.Client.IAsynchronousClient asyncClient, CShocker.GeneratedClients.OpenShockClientv1.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets online devices statistics 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>StatsResponseLegacyDataResponse</returns>
        public StatsResponseLegacyDataResponse PublicGetOnlineDevicesStatistics()
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<StatsResponseLegacyDataResponse> localVarResponse = PublicGetOnlineDevicesStatisticsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets online devices statistics 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of StatsResponseLegacyDataResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<StatsResponseLegacyDataResponse> PublicGetOnlineDevicesStatisticsWithHttpInfo()
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<StatsResponseLegacyDataResponse>("/1/public/stats", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicGetOnlineDevicesStatistics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets online devices statistics 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatsResponseLegacyDataResponse</returns>
        public async System.Threading.Tasks.Task<StatsResponseLegacyDataResponse> PublicGetOnlineDevicesStatisticsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<StatsResponseLegacyDataResponse> localVarResponse = await PublicGetOnlineDevicesStatisticsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets online devices statistics 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatsResponseLegacyDataResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<StatsResponseLegacyDataResponse>> PublicGetOnlineDevicesStatisticsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<StatsResponseLegacyDataResponse>("/1/public/stats", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicGetOnlineDevicesStatistics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the version of the OpenShock backend. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>BackendInfoResponseLegacyDataResponse</returns>
        public BackendInfoResponseLegacyDataResponse VersionGetBackendInfo()
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<BackendInfoResponseLegacyDataResponse> localVarResponse = VersionGetBackendInfoWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the version of the OpenShock backend. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of BackendInfoResponseLegacyDataResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<BackendInfoResponseLegacyDataResponse> VersionGetBackendInfoWithHttpInfo()
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<BackendInfoResponseLegacyDataResponse>("/1", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VersionGetBackendInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the version of the OpenShock backend. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BackendInfoResponseLegacyDataResponse</returns>
        public async System.Threading.Tasks.Task<BackendInfoResponseLegacyDataResponse> VersionGetBackendInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<BackendInfoResponseLegacyDataResponse> localVarResponse = await VersionGetBackendInfoWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the version of the OpenShock backend. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BackendInfoResponseLegacyDataResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<BackendInfoResponseLegacyDataResponse>> VersionGetBackendInfoWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<BackendInfoResponseLegacyDataResponse>("/1", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VersionGetBackendInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
