/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CShocker.GeneratedClients.OpenShockClientv1.Client;
using CShocker.GeneratedClients.OpenShockClientv1.Model;

namespace CShocker.GeneratedClients.OpenShockClientv1.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicShockerSharesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets information about a public share.
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>PublicShareResponseLegacyDataResponse</returns>
        PublicShareResponseLegacyDataResponse PublicGetPublicShare(Guid publicShareId);

        /// <summary>
        /// Gets information about a public share.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>ApiResponse of PublicShareResponseLegacyDataResponse</returns>
        ApiResponse<PublicShareResponseLegacyDataResponse> PublicGetPublicShareWithHttpInfo(Guid publicShareId);
        /// <summary>
        /// Add a shocker to a public share
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        LegacyEmptyResponse ShareLinksAddShocker(Guid publicShareId, Guid shockerId);

        /// <summary>
        /// Add a shocker to a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        ApiResponse<LegacyEmptyResponse> ShareLinksAddShockerWithHttpInfo(Guid publicShareId, Guid shockerId);
        /// <summary>
        /// Create a new public share
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <returns>GuidLegacyDataResponse</returns>
        GuidLegacyDataResponse ShareLinksCreatePublicShare(PublicShareCreate? publicShareCreate = default);

        /// <summary>
        /// Create a new public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <returns>ApiResponse of GuidLegacyDataResponse</returns>
        ApiResponse<GuidLegacyDataResponse> ShareLinksCreatePublicShareWithHttpInfo(PublicShareCreate? publicShareCreate = default);
        /// <summary>
        /// Deletes a public share
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        LegacyEmptyResponse ShareLinksDeletePublicShare(Guid publicShareId);

        /// <summary>
        /// Deletes a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        ApiResponse<LegacyEmptyResponse> ShareLinksDeletePublicShareWithHttpInfo(Guid publicShareId);
        /// <summary>
        /// Edit a shocker in a public share
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <returns>string</returns>
        string ShareLinksEditShocker(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default);

        /// <summary>
        /// Edit a shocker in a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ShareLinksEditShockerWithHttpInfo(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default);
        /// <summary>
        /// Get all public shares for the current user
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>OwnPublicShareResponseArrayLegacyDataResponse</returns>
        OwnPublicShareResponseArrayLegacyDataResponse ShareLinksList();

        /// <summary>
        /// Get all public shares for the current user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of OwnPublicShareResponseArrayLegacyDataResponse</returns>
        ApiResponse<OwnPublicShareResponseArrayLegacyDataResponse> ShareLinksListWithHttpInfo();
        /// <summary>
        /// Pause a shocker in a public share
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <returns>PauseReasonLegacyDataResponse</returns>
        PauseReasonLegacyDataResponse ShareLinksPauseShocker(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default);

        /// <summary>
        /// Pause a shocker in a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <returns>ApiResponse of PauseReasonLegacyDataResponse</returns>
        ApiResponse<PauseReasonLegacyDataResponse> ShareLinksPauseShockerWithHttpInfo(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default);
        /// <summary>
        /// Remove a shocker from a public share
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        LegacyEmptyResponse ShareLinksRemoveShocker(Guid publicShareId, Guid shockerId);

        /// <summary>
        /// Remove a shocker from a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        ApiResponse<LegacyEmptyResponse> ShareLinksRemoveShockerWithHttpInfo(Guid publicShareId, Guid shockerId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicShockerSharesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets information about a public share.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PublicShareResponseLegacyDataResponse</returns>
        System.Threading.Tasks.Task<PublicShareResponseLegacyDataResponse> PublicGetPublicShareAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets information about a public share.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PublicShareResponseLegacyDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PublicShareResponseLegacyDataResponse>> PublicGetPublicShareWithHttpInfoAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Add a shocker to a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        System.Threading.Tasks.Task<LegacyEmptyResponse> ShareLinksAddShockerAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Add a shocker to a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LegacyEmptyResponse>> ShareLinksAddShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create a new public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GuidLegacyDataResponse</returns>
        System.Threading.Tasks.Task<GuidLegacyDataResponse> ShareLinksCreatePublicShareAsync(PublicShareCreate? publicShareCreate = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a new public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GuidLegacyDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GuidLegacyDataResponse>> ShareLinksCreatePublicShareWithHttpInfoAsync(PublicShareCreate? publicShareCreate = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Deletes a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        System.Threading.Tasks.Task<LegacyEmptyResponse> ShareLinksDeletePublicShareAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Deletes a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LegacyEmptyResponse>> ShareLinksDeletePublicShareWithHttpInfoAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Edit a shocker in a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ShareLinksEditShockerAsync(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Edit a shocker in a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ShareLinksEditShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get all public shares for the current user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OwnPublicShareResponseArrayLegacyDataResponse</returns>
        System.Threading.Tasks.Task<OwnPublicShareResponseArrayLegacyDataResponse> ShareLinksListAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all public shares for the current user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OwnPublicShareResponseArrayLegacyDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OwnPublicShareResponseArrayLegacyDataResponse>> ShareLinksListWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Pause a shocker in a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PauseReasonLegacyDataResponse</returns>
        System.Threading.Tasks.Task<PauseReasonLegacyDataResponse> ShareLinksPauseShockerAsync(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Pause a shocker in a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PauseReasonLegacyDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PauseReasonLegacyDataResponse>> ShareLinksPauseShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Remove a shocker from a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        System.Threading.Tasks.Task<LegacyEmptyResponse> ShareLinksRemoveShockerAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Remove a shocker from a public share
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LegacyEmptyResponse>> ShareLinksRemoveShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicShockerSharesApi : IPublicShockerSharesApiSync, IPublicShockerSharesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PublicShockerSharesApi : IDisposable, IPublicShockerSharesApi
    {
        private CShocker.GeneratedClients.OpenShockClientv1.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PublicShockerSharesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PublicShockerSharesApi(string basePath)
        {
            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PublicShockerSharesApi(CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PublicShockerSharesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PublicShockerSharesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PublicShockerSharesApi(HttpClient client, CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShockerSharesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PublicShockerSharesApi(CShocker.GeneratedClients.OpenShockClientv1.Client.ISynchronousClient client, CShocker.GeneratedClients.OpenShockClientv1.Client.IAsynchronousClient asyncClient, CShocker.GeneratedClients.OpenShockClientv1.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets information about a public share. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>PublicShareResponseLegacyDataResponse</returns>
        public PublicShareResponseLegacyDataResponse PublicGetPublicShare(Guid publicShareId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PublicShareResponseLegacyDataResponse> localVarResponse = PublicGetPublicShareWithHttpInfo(publicShareId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets information about a public share. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>ApiResponse of PublicShareResponseLegacyDataResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PublicShareResponseLegacyDataResponse> PublicGetPublicShareWithHttpInfo(Guid publicShareId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<PublicShareResponseLegacyDataResponse>("/1/public/shares/links/{publicShareId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicGetPublicShare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets information about a public share. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PublicShareResponseLegacyDataResponse</returns>
        public async System.Threading.Tasks.Task<PublicShareResponseLegacyDataResponse> PublicGetPublicShareAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PublicShareResponseLegacyDataResponse> localVarResponse = await PublicGetPublicShareWithHttpInfoAsync(publicShareId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets information about a public share. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PublicShareResponseLegacyDataResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PublicShareResponseLegacyDataResponse>> PublicGetPublicShareWithHttpInfoAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PublicShareResponseLegacyDataResponse>("/1/public/shares/links/{publicShareId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicGetPublicShare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a shocker to a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        public LegacyEmptyResponse ShareLinksAddShocker(Guid publicShareId, Guid shockerId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = ShareLinksAddShockerWithHttpInfo(publicShareId, shockerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a shocker to a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> ShareLinksAddShockerWithHttpInfo(Guid publicShareId, Guid shockerId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LegacyEmptyResponse>("/1/shares/links/{publicShareId}/{shockerId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksAddShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a shocker to a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        public async System.Threading.Tasks.Task<LegacyEmptyResponse> ShareLinksAddShockerAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = await ShareLinksAddShockerWithHttpInfoAsync(publicShareId, shockerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a shocker to a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse>> ShareLinksAddShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LegacyEmptyResponse>("/1/shares/links/{publicShareId}/{shockerId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksAddShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <returns>GuidLegacyDataResponse</returns>
        public GuidLegacyDataResponse ShareLinksCreatePublicShare(PublicShareCreate? publicShareCreate = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<GuidLegacyDataResponse> localVarResponse = ShareLinksCreatePublicShareWithHttpInfo(publicShareCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <returns>ApiResponse of GuidLegacyDataResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<GuidLegacyDataResponse> ShareLinksCreatePublicShareWithHttpInfo(PublicShareCreate? publicShareCreate = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = publicShareCreate;

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<GuidLegacyDataResponse>("/1/shares/links", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksCreatePublicShare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GuidLegacyDataResponse</returns>
        public async System.Threading.Tasks.Task<GuidLegacyDataResponse> ShareLinksCreatePublicShareAsync(PublicShareCreate? publicShareCreate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<GuidLegacyDataResponse> localVarResponse = await ShareLinksCreatePublicShareWithHttpInfoAsync(publicShareCreate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareCreate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GuidLegacyDataResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<GuidLegacyDataResponse>> ShareLinksCreatePublicShareWithHttpInfoAsync(PublicShareCreate? publicShareCreate = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = publicShareCreate;

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<GuidLegacyDataResponse>("/1/shares/links", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksCreatePublicShare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        public LegacyEmptyResponse ShareLinksDeletePublicShare(Guid publicShareId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = ShareLinksDeletePublicShareWithHttpInfo(publicShareId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> ShareLinksDeletePublicShareWithHttpInfo(Guid publicShareId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<LegacyEmptyResponse>("/1/shares/links/{publicShareId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksDeletePublicShare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        public async System.Threading.Tasks.Task<LegacyEmptyResponse> ShareLinksDeletePublicShareAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = await ShareLinksDeletePublicShareWithHttpInfoAsync(publicShareId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse>> ShareLinksDeletePublicShareWithHttpInfoAsync(Guid publicShareId, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<LegacyEmptyResponse>("/1/shares/links/{publicShareId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksDeletePublicShare", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Edit a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <returns>string</returns>
        public string ShareLinksEditShocker(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<string> localVarResponse = ShareLinksEditShockerWithHttpInfo(publicShareId, shockerId, publicShareEditShocker);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Edit a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<string> ShareLinksEditShockerWithHttpInfo(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter
            localVarRequestOptions.Data = publicShareEditShocker;

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<string>("/1/shares/links/{publicShareId}/{shockerId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksEditShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Edit a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ShareLinksEditShockerAsync(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<string> localVarResponse = await ShareLinksEditShockerWithHttpInfoAsync(publicShareId, shockerId, publicShareEditShocker, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Edit a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="publicShareEditShocker"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<string>> ShareLinksEditShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, PublicShareEditShocker? publicShareEditShocker = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter
            localVarRequestOptions.Data = publicShareEditShocker;

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<string>("/1/shares/links/{publicShareId}/{shockerId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksEditShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all public shares for the current user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>OwnPublicShareResponseArrayLegacyDataResponse</returns>
        public OwnPublicShareResponseArrayLegacyDataResponse ShareLinksList()
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<OwnPublicShareResponseArrayLegacyDataResponse> localVarResponse = ShareLinksListWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all public shares for the current user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of OwnPublicShareResponseArrayLegacyDataResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<OwnPublicShareResponseArrayLegacyDataResponse> ShareLinksListWithHttpInfo()
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<OwnPublicShareResponseArrayLegacyDataResponse>("/1/shares/links", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all public shares for the current user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OwnPublicShareResponseArrayLegacyDataResponse</returns>
        public async System.Threading.Tasks.Task<OwnPublicShareResponseArrayLegacyDataResponse> ShareLinksListAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<OwnPublicShareResponseArrayLegacyDataResponse> localVarResponse = await ShareLinksListWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all public shares for the current user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OwnPublicShareResponseArrayLegacyDataResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<OwnPublicShareResponseArrayLegacyDataResponse>> ShareLinksListWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<OwnPublicShareResponseArrayLegacyDataResponse>("/1/shares/links", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Pause a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <returns>PauseReasonLegacyDataResponse</returns>
        public PauseReasonLegacyDataResponse ShareLinksPauseShocker(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PauseReasonLegacyDataResponse> localVarResponse = ShareLinksPauseShockerWithHttpInfo(publicShareId, shockerId, pauseRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Pause a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <returns>ApiResponse of PauseReasonLegacyDataResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PauseReasonLegacyDataResponse> ShareLinksPauseShockerWithHttpInfo(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter
            localVarRequestOptions.Data = pauseRequest;

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PauseReasonLegacyDataResponse>("/1/shares/links/{publicShareId}/{shockerId}/pause", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksPauseShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Pause a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PauseReasonLegacyDataResponse</returns>
        public async System.Threading.Tasks.Task<PauseReasonLegacyDataResponse> ShareLinksPauseShockerAsync(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PauseReasonLegacyDataResponse> localVarResponse = await ShareLinksPauseShockerWithHttpInfoAsync(publicShareId, shockerId, pauseRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Pause a shocker in a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="pauseRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PauseReasonLegacyDataResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<PauseReasonLegacyDataResponse>> ShareLinksPauseShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, PauseRequest? pauseRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter
            localVarRequestOptions.Data = pauseRequest;

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PauseReasonLegacyDataResponse>("/1/shares/links/{publicShareId}/{shockerId}/pause", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksPauseShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remove a shocker from a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        public LegacyEmptyResponse ShareLinksRemoveShocker(Guid publicShareId, Guid shockerId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = ShareLinksRemoveShockerWithHttpInfo(publicShareId, shockerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Remove a shocker from a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> ShareLinksRemoveShockerWithHttpInfo(Guid publicShareId, Guid shockerId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<LegacyEmptyResponse>("/1/shares/links/{publicShareId}/{shockerId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksRemoveShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remove a shocker from a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        public async System.Threading.Tasks.Task<LegacyEmptyResponse> ShareLinksRemoveShockerAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = await ShareLinksRemoveShockerWithHttpInfoAsync(publicShareId, shockerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Remove a shocker from a public share 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="publicShareId"></param>
        /// <param name="shockerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse>> ShareLinksRemoveShockerWithHttpInfoAsync(Guid publicShareId, Guid shockerId, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("publicShareId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(publicShareId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shockerId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shockerId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<LegacyEmptyResponse>("/1/shares/links/{publicShareId}/{shockerId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShareLinksRemoveShocker", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
