/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// Request DTO for updating a configuration item. Either OpenShock.API.Controller.Admin.DTOs.ConfigurationUpdateItemRequest.Description or OpenShock.API.Controller.Admin.DTOs.ConfigurationUpdateItemRequest.Value (or both) may be provided. If both are null, no update action is performed.
    /// </summary>
    [DataContract(Name = "ConfigurationUpdateItemRequest")]
    public partial class ConfigurationUpdateItemRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationUpdateItemRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfigurationUpdateItemRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationUpdateItemRequest" /> class.
        /// </summary>
        /// <param name="name">The name of the configuration item to update. Must consist only of uppercase letters and underscores. (required).</param>
        /// <param name="description">(Optional) New description for the configuration item..</param>
        /// <param name="value">(Optional) New value for the configuration item. Must match the format expected by its existing OpenShock.Common.OpenShockDb.ConfigurationValueType..</param>
        public ConfigurationUpdateItemRequest(string name = default, string description = default, string value = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ConfigurationUpdateItemRequest and cannot be null");
            }
            this.Name = name;
            this.Description = description;
            this.Value = value;
        }

        /// <summary>
        /// The name of the configuration item to update. Must consist only of uppercase letters and underscores.
        /// </summary>
        /// <value>The name of the configuration item to update. Must consist only of uppercase letters and underscores.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// (Optional) New description for the configuration item.
        /// </summary>
        /// <value>(Optional) New description for the configuration item.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// (Optional) New value for the configuration item. Must match the format expected by its existing OpenShock.Common.OpenShockDb.ConfigurationValueType.
        /// </summary>
        /// <value>(Optional) New value for the configuration item. Must match the format expected by its existing OpenShock.Common.OpenShockDb.ConfigurationValueType.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigurationUpdateItemRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
