/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// LcgNodeResponse
    /// </summary>
    [DataContract(Name = "LcgNodeResponse")]
    public partial class LcgNodeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LcgNodeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LcgNodeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LcgNodeResponse" /> class.
        /// </summary>
        /// <param name="fqdn">fqdn (required).</param>
        /// <param name="country">country (required).</param>
        public LcgNodeResponse(string fqdn = default, string country = default)
        {
            // to ensure "fqdn" is required (not null)
            if (fqdn == null)
            {
                throw new ArgumentNullException("fqdn is a required property for LcgNodeResponse and cannot be null");
            }
            this.Fqdn = fqdn;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for LcgNodeResponse and cannot be null");
            }
            this.Country = country;
        }

        /// <summary>
        /// Gets or Sets Fqdn
        /// </summary>
        [DataMember(Name = "fqdn", IsRequired = true, EmitDefaultValue = true)]
        public string Fqdn { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LcgNodeResponse {\n");
            sb.Append("  Fqdn: ").Append(Fqdn).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
