/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// OAuthConnectionResponse
    /// </summary>
    [DataContract(Name = "OAuthConnectionResponse")]
    public partial class OAuthConnectionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthConnectionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OAuthConnectionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthConnectionResponse" /> class.
        /// </summary>
        /// <param name="providerKey">providerKey (required).</param>
        /// <param name="externalId">externalId (required).</param>
        /// <param name="displayName">displayName (required).</param>
        /// <param name="linkedAt">linkedAt (required).</param>
        public OAuthConnectionResponse(string providerKey = default, string externalId = default, string displayName = default, DateTime linkedAt = default)
        {
            // to ensure "providerKey" is required (not null)
            if (providerKey == null)
            {
                throw new ArgumentNullException("providerKey is a required property for OAuthConnectionResponse and cannot be null");
            }
            this.ProviderKey = providerKey;
            // to ensure "externalId" is required (not null)
            if (externalId == null)
            {
                throw new ArgumentNullException("externalId is a required property for OAuthConnectionResponse and cannot be null");
            }
            this.ExternalId = externalId;
            // to ensure "displayName" is required (not null)
            if (displayName == null)
            {
                throw new ArgumentNullException("displayName is a required property for OAuthConnectionResponse and cannot be null");
            }
            this.DisplayName = displayName;
            this.LinkedAt = linkedAt;
        }

        /// <summary>
        /// Gets or Sets ProviderKey
        /// </summary>
        [DataMember(Name = "providerKey", IsRequired = true, EmitDefaultValue = true)]
        public string ProviderKey { get; set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [DataMember(Name = "externalId", IsRequired = true, EmitDefaultValue = true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "displayName", IsRequired = true, EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets LinkedAt
        /// </summary>
        [DataMember(Name = "linkedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime LinkedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OAuthConnectionResponse {\n");
            sb.Append("  ProviderKey: ").Append(ProviderKey).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  LinkedAt: ").Append(LinkedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
