/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// Defines PasswordHashingAlgorithm
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PasswordHashingAlgorithm
    {
        /// <summary>
        /// Enum BCrypt for value: BCrypt
        /// </summary>
        [EnumMember(Value = "BCrypt")]
        BCrypt = 1,

        /// <summary>
        /// Enum PBKDF2 for value: PBKDF2
        /// </summary>
        [EnumMember(Value = "PBKDF2")]
        PBKDF2 = 2,

        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 3
    }

}
