/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// PublicShareResponse
    /// </summary>
    [DataContract(Name = "PublicShareResponse")]
    public partial class PublicShareResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShareResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicShareResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShareResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="createdOn">createdOn (required).</param>
        /// <param name="expiresOn">expiresOn.</param>
        /// <param name="author">author (required).</param>
        /// <param name="devices">devices.</param>
        public PublicShareResponse(Guid id = default, string name = default, DateTime createdOn = default, DateTime? expiresOn = default, BasicUserInfo author = default, List<PublicShareDevice> devices = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PublicShareResponse and cannot be null");
            }
            this.Name = name;
            this.CreatedOn = createdOn;
            // to ensure "author" is required (not null)
            if (author == null)
            {
                throw new ArgumentNullException("author is a required property for PublicShareResponse and cannot be null");
            }
            this.Author = author;
            this.ExpiresOn = expiresOn;
            this.Devices = devices;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        [DataMember(Name = "createdOn", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresOn
        /// </summary>
        [DataMember(Name = "expiresOn", EmitDefaultValue = true)]
        public DateTime? ExpiresOn { get; set; }

        /// <summary>
        /// Gets or Sets Author
        /// </summary>
        [DataMember(Name = "author", IsRequired = true, EmitDefaultValue = true)]
        public BasicUserInfo Author { get; set; }

        /// <summary>
        /// Gets or Sets Devices
        /// </summary>
        [DataMember(Name = "devices", EmitDefaultValue = false)]
        public List<PublicShareDevice> Devices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicShareResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  ExpiresOn: ").Append(ExpiresOn).Append("\n");
            sb.Append("  Author: ").Append(Author).Append("\n");
            sb.Append("  Devices: ").Append(Devices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
