/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// PublicShareShocker
    /// </summary>
    [DataContract(Name = "PublicShareShocker")]
    public partial class PublicShareShocker : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShareShocker" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicShareShocker() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicShareShocker" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="permissions">permissions (required).</param>
        /// <param name="limits">limits (required).</param>
        /// <param name="paused">An integer representing the reason(s) for the shocker being paused, expressed as a bitfield where reasons are OR&#39;d together.  Each bit corresponds to: - 1: Shocker - 2: UserShare - 4: PublicShare  For example, a value of 6 (2 | 4) indicates both &#39;UserShare&#39; and &#39;PublicShare&#39; reasons. (required).</param>
        public PublicShareShocker(Guid id = default, string name = default, ShockerPermissions permissions = default, ShockerLimits limits = default, int paused = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PublicShareShocker and cannot be null");
            }
            this.Name = name;
            // to ensure "permissions" is required (not null)
            if (permissions == null)
            {
                throw new ArgumentNullException("permissions is a required property for PublicShareShocker and cannot be null");
            }
            this.Permissions = permissions;
            // to ensure "limits" is required (not null)
            if (limits == null)
            {
                throw new ArgumentNullException("limits is a required property for PublicShareShocker and cannot be null");
            }
            this.Limits = limits;
            this.Paused = paused;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name = "permissions", IsRequired = true, EmitDefaultValue = true)]
        public ShockerPermissions Permissions { get; set; }

        /// <summary>
        /// Gets or Sets Limits
        /// </summary>
        [DataMember(Name = "limits", IsRequired = true, EmitDefaultValue = true)]
        public ShockerLimits Limits { get; set; }

        /// <summary>
        /// An integer representing the reason(s) for the shocker being paused, expressed as a bitfield where reasons are OR&#39;d together.  Each bit corresponds to: - 1: Shocker - 2: UserShare - 4: PublicShare  For example, a value of 6 (2 | 4) indicates both &#39;UserShare&#39; and &#39;PublicShare&#39; reasons.
        /// </summary>
        /// <value>An integer representing the reason(s) for the shocker being paused, expressed as a bitfield where reasons are OR&#39;d together.  Each bit corresponds to: - 1: Shocker - 2: UserShare - 4: PublicShare  For example, a value of 6 (2 | 4) indicates both &#39;UserShare&#39; and &#39;PublicShare&#39; reasons.</value>
        /*
        <example>6</example>
        */
        [DataMember(Name = "paused", IsRequired = true, EmitDefaultValue = true)]
        public int Paused { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicShareShocker {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  Paused: ").Append(Paused).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
