/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// ShareCodeInfo
    /// </summary>
    [DataContract(Name = "ShareCodeInfo")]
    public partial class ShareCodeInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareCodeInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShareCodeInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareCodeInfo" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="createdOn">createdOn (required).</param>
        public ShareCodeInfo(Guid id = default, DateTime createdOn = default)
        {
            this.Id = id;
            this.CreatedOn = createdOn;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        [DataMember(Name = "createdOn", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShareCodeInfo {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
