/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// Defines ShockerModelType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ShockerModelType
    {
        /// <summary>
        /// Enum CaiXianlin for value: CaiXianlin
        /// </summary>
        [EnumMember(Value = "CaiXianlin")]
        CaiXianlin = 1,

        /// <summary>
        /// Enum PetTrainer for value: PetTrainer
        /// </summary>
        [EnumMember(Value = "PetTrainer")]
        PetTrainer = 2,

        /// <summary>
        /// Enum Petrainer998DR for value: Petrainer998DR
        /// </summary>
        [EnumMember(Value = "Petrainer998DR")]
        Petrainer998DR = 3,

        /// <summary>
        /// Enum WellturnT330 for value: WellturnT330
        /// </summary>
        [EnumMember(Value = "WellturnT330")]
        WellturnT330 = 4
    }

}
