/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClientv1.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClientv1.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClientv1.Model
{
    /// <summary>
    /// StatsResponse
    /// </summary>
    [DataContract(Name = "StatsResponse")]
    public partial class StatsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StatsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StatsResponse" /> class.
        /// </summary>
        /// <param name="devicesOnline">devicesOnline (required).</param>
        public StatsResponse(long devicesOnline = default)
        {
            this.DevicesOnline = devicesOnline;
        }

        /// <summary>
        /// Gets or Sets DevicesOnline
        /// </summary>
        [DataMember(Name = "devicesOnline", IsRequired = true, EmitDefaultValue = true)]
        public long DevicesOnline { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatsResponse {\n");
            sb.Append("  DevicesOnline: ").Append(DevicesOnline).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
