/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CShocker.GeneratedClients.OpenShockClient.Client;
using CShocker.GeneratedClients.OpenShockClient.Model;

namespace CShocker.GeneratedClients.OpenShockClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Check if a username is available
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <returns>UsernameCheckResponse</returns>
        UsernameCheckResponse AccountCheckUsername(ChangeUsernameRequest? changeUsernameRequest = default);

        /// <summary>
        /// Check if a username is available
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <returns>ApiResponse of UsernameCheckResponse</returns>
        ApiResponse<UsernameCheckResponse> AccountCheckUsernameWithHttpInfo(ChangeUsernameRequest? changeUsernameRequest = default);
        /// <summary>
        /// Authenticate a user
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <returns>LoginV2OkResponse</returns>
        LoginV2OkResponse AccountLoginV2(LoginV2? loginV2 = default);

        /// <summary>
        /// Authenticate a user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <returns>ApiResponse of LoginV2OkResponse</returns>
        ApiResponse<LoginV2OkResponse> AccountLoginV2WithHttpInfo(LoginV2? loginV2 = default);
        /// <summary>
        /// Initiate a password reset
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns></returns>
        void AccountPasswordResetInitiateV2(PasswordResetRequestV2? passwordResetRequestV2 = default);

        /// <summary>
        /// Initiate a password reset
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AccountPasswordResetInitiateV2WithHttpInfo(PasswordResetRequestV2? passwordResetRequestV2 = default);
        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead.
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns></returns>
        [Obsolete]
        void AccountPasswordResetInitiateV2Legacy(PasswordResetRequestV2? passwordResetRequestV2 = default);

        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        [Obsolete]
        ApiResponse<Object> AccountPasswordResetInitiateV2LegacyWithHttpInfo(PasswordResetRequestV2? passwordResetRequestV2 = default);
        /// <summary>
        /// Signs up a new user
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <returns></returns>
        void AccountSignUpV2(SignUpV2? signUpV2 = default);

        /// <summary>
        /// Signs up a new user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AccountSignUpV2WithHttpInfo(SignUpV2? signUpV2 = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Check if a username is available
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UsernameCheckResponse</returns>
        System.Threading.Tasks.Task<UsernameCheckResponse> AccountCheckUsernameAsync(ChangeUsernameRequest? changeUsernameRequest = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Check if a username is available
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UsernameCheckResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<UsernameCheckResponse>> AccountCheckUsernameWithHttpInfoAsync(ChangeUsernameRequest? changeUsernameRequest = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Authenticate a user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginV2OkResponse</returns>
        System.Threading.Tasks.Task<LoginV2OkResponse> AccountLoginV2Async(LoginV2? loginV2 = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Authenticate a user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginV2OkResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginV2OkResponse>> AccountLoginV2WithHttpInfoAsync(LoginV2? loginV2 = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Initiate a password reset
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AccountPasswordResetInitiateV2Async(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Initiate a password reset
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AccountPasswordResetInitiateV2WithHttpInfoAsync(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        [Obsolete]
        System.Threading.Tasks.Task AccountPasswordResetInitiateV2LegacyAsync(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<Object>> AccountPasswordResetInitiateV2LegacyWithHttpInfoAsync(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Signs up a new user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AccountSignUpV2Async(SignUpV2? signUpV2 = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Signs up a new user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AccountSignUpV2WithHttpInfoAsync(SignUpV2? signUpV2 = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApi : IAccountApiSync, IAccountApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountApi : IDisposable, IAccountApi
    {
        private CShocker.GeneratedClients.OpenShockClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AccountApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AccountApi(string basePath)
        {
            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AccountApi(CShocker.GeneratedClients.OpenShockClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, CShocker.GeneratedClients.OpenShockClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AccountApi(CShocker.GeneratedClients.OpenShockClient.Client.ISynchronousClient client, CShocker.GeneratedClients.OpenShockClient.Client.IAsynchronousClient asyncClient, CShocker.GeneratedClients.OpenShockClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CShocker.GeneratedClients.OpenShockClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Check if a username is available 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <returns>UsernameCheckResponse</returns>
        public UsernameCheckResponse AccountCheckUsername(ChangeUsernameRequest? changeUsernameRequest = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<UsernameCheckResponse> localVarResponse = AccountCheckUsernameWithHttpInfo(changeUsernameRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Check if a username is available 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <returns>ApiResponse of UsernameCheckResponse</returns>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<UsernameCheckResponse> AccountCheckUsernameWithHttpInfo(ChangeUsernameRequest? changeUsernameRequest = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = changeUsernameRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UsernameCheckResponse>("/2/account/username/check", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountCheckUsername", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Check if a username is available 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UsernameCheckResponse</returns>
        public async System.Threading.Tasks.Task<UsernameCheckResponse> AccountCheckUsernameAsync(ChangeUsernameRequest? changeUsernameRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<UsernameCheckResponse> localVarResponse = await AccountCheckUsernameWithHttpInfoAsync(changeUsernameRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Check if a username is available 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeUsernameRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UsernameCheckResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<UsernameCheckResponse>> AccountCheckUsernameWithHttpInfoAsync(ChangeUsernameRequest? changeUsernameRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = changeUsernameRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<UsernameCheckResponse>("/2/account/username/check", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountCheckUsername", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Authenticate a user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <returns>LoginV2OkResponse</returns>
        public LoginV2OkResponse AccountLoginV2(LoginV2? loginV2 = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LoginV2OkResponse> localVarResponse = AccountLoginV2WithHttpInfo(loginV2);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Authenticate a user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <returns>ApiResponse of LoginV2OkResponse</returns>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LoginV2OkResponse> AccountLoginV2WithHttpInfo(LoginV2? loginV2 = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = loginV2;


            // make the HTTP request
            var localVarResponse = this.Client.Post<LoginV2OkResponse>("/2/account/login", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountLoginV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Authenticate a user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginV2OkResponse</returns>
        public async System.Threading.Tasks.Task<LoginV2OkResponse> AccountLoginV2Async(LoginV2? loginV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LoginV2OkResponse> localVarResponse = await AccountLoginV2WithHttpInfoAsync(loginV2, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Authenticate a user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loginV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginV2OkResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LoginV2OkResponse>> AccountLoginV2WithHttpInfoAsync(LoginV2? loginV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = loginV2;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LoginV2OkResponse>("/2/account/login", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountLoginV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initiate a password reset 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns></returns>
        public void AccountPasswordResetInitiateV2(PasswordResetRequestV2? passwordResetRequestV2 = default)
        {
            AccountPasswordResetInitiateV2WithHttpInfo(passwordResetRequestV2);
        }

        /// <summary>
        /// Initiate a password reset 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<Object> AccountPasswordResetInitiateV2WithHttpInfo(PasswordResetRequestV2? passwordResetRequestV2 = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = passwordResetRequestV2;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/2/account/password-reset", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountPasswordResetInitiateV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initiate a password reset 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AccountPasswordResetInitiateV2Async(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await AccountPasswordResetInitiateV2WithHttpInfoAsync(passwordResetRequestV2, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Initiate a password reset 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<Object>> AccountPasswordResetInitiateV2WithHttpInfoAsync(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = passwordResetRequestV2;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/2/account/password-reset", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountPasswordResetInitiateV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns></returns>
        [Obsolete]
        public void AccountPasswordResetInitiateV2Legacy(PasswordResetRequestV2? passwordResetRequestV2 = default)
        {
            AccountPasswordResetInitiateV2LegacyWithHttpInfo(passwordResetRequestV2);
        }

        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        [Obsolete]
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<Object> AccountPasswordResetInitiateV2LegacyWithHttpInfo(PasswordResetRequestV2? passwordResetRequestV2 = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = passwordResetRequestV2;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/2/account/reset-password", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountPasswordResetInitiateV2Legacy", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task AccountPasswordResetInitiateV2LegacyAsync(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await AccountPasswordResetInitiateV2LegacyWithHttpInfoAsync(passwordResetRequestV2, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Initiate a password reset. Deprecated: use POST /password-reset instead. 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passwordResetRequestV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<Object>> AccountPasswordResetInitiateV2LegacyWithHttpInfoAsync(PasswordResetRequestV2? passwordResetRequestV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = passwordResetRequestV2;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/2/account/reset-password", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountPasswordResetInitiateV2Legacy", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Signs up a new user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <returns></returns>
        public void AccountSignUpV2(SignUpV2? signUpV2 = default)
        {
            AccountSignUpV2WithHttpInfo(signUpV2);
        }

        /// <summary>
        /// Signs up a new user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<Object> AccountSignUpV2WithHttpInfo(SignUpV2? signUpV2 = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = signUpV2;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/2/account/signup", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountSignUpV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Signs up a new user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AccountSignUpV2Async(SignUpV2? signUpV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await AccountSignUpV2WithHttpInfoAsync(signUpV2, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Signs up a new user 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signUpV2"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<Object>> AccountSignUpV2WithHttpInfoAsync(SignUpV2? signUpV2 = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = signUpV2;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/2/account/signup", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AccountSignUpV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
