/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CShocker.GeneratedClients.OpenShockClient.Client;
using CShocker.GeneratedClients.OpenShockClient.Model;

namespace CShocker.GeneratedClients.OpenShockClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHubEndpointsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets the best suited LCG node for the client
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <returns>LcgNodeResponseV2</returns>
        LcgNodeResponseV2 DeviceGetLiveControlGatewayV2(int? version = default);

        /// <summary>
        /// Gets the best suited LCG node for the client
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <returns>ApiResponse of LcgNodeResponseV2</returns>
        ApiResponse<LcgNodeResponseV2> DeviceGetLiveControlGatewayV2WithHttpInfo(int? version = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHubEndpointsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets the best suited LCG node for the client
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LcgNodeResponseV2</returns>
        System.Threading.Tasks.Task<LcgNodeResponseV2> DeviceGetLiveControlGatewayV2Async(int? version = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the best suited LCG node for the client
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LcgNodeResponseV2)</returns>
        System.Threading.Tasks.Task<ApiResponse<LcgNodeResponseV2>> DeviceGetLiveControlGatewayV2WithHttpInfoAsync(int? version = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHubEndpointsApi : IHubEndpointsApiSync, IHubEndpointsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class HubEndpointsApi : IDisposable, IHubEndpointsApi
    {
        private CShocker.GeneratedClients.OpenShockClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public HubEndpointsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public HubEndpointsApi(string basePath)
        {
            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public HubEndpointsApi(CShocker.GeneratedClients.OpenShockClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HubEndpointsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HubEndpointsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HubEndpointsApi(HttpClient client, CShocker.GeneratedClients.OpenShockClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HubEndpointsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public HubEndpointsApi(CShocker.GeneratedClients.OpenShockClient.Client.ISynchronousClient client, CShocker.GeneratedClients.OpenShockClient.Client.IAsynchronousClient asyncClient, CShocker.GeneratedClients.OpenShockClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CShocker.GeneratedClients.OpenShockClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the best suited LCG node for the client 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <returns>LcgNodeResponseV2</returns>
        public LcgNodeResponseV2 DeviceGetLiveControlGatewayV2(int? version = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LcgNodeResponseV2> localVarResponse = DeviceGetLiveControlGatewayV2WithHttpInfo(version);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the best suited LCG node for the client 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <returns>ApiResponse of LcgNodeResponseV2</returns>
        public CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LcgNodeResponseV2> DeviceGetLiveControlGatewayV2WithHttpInfo(int? version = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (version != null)
            {
                localVarRequestOptions.QueryParameters.Add(CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.ParameterToMultiMap("", "version", version));
            }

            // authentication (HubToken) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("DeviceToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("DeviceToken", this.Configuration.GetApiKeyWithPrefix("DeviceToken"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LcgNodeResponseV2>("/2/device/assignLCG", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeviceGetLiveControlGatewayV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the best suited LCG node for the client 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LcgNodeResponseV2</returns>
        public async System.Threading.Tasks.Task<LcgNodeResponseV2> DeviceGetLiveControlGatewayV2Async(int? version = default, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LcgNodeResponseV2> localVarResponse = await DeviceGetLiveControlGatewayV2WithHttpInfoAsync(version, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the best suited LCG node for the client 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LcgNodeResponseV2)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClient.Client.ApiResponse<LcgNodeResponseV2>> DeviceGetLiveControlGatewayV2WithHttpInfoAsync(int? version = default, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (version != null)
            {
                localVarRequestOptions.QueryParameters.Add(CShocker.GeneratedClients.OpenShockClient.Client.ClientUtils.ParameterToMultiMap("", "version", version));
            }

            // authentication (HubToken) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("DeviceToken")))
            {
                localVarRequestOptions.HeaderParameters.Add("DeviceToken", this.Configuration.GetApiKeyWithPrefix("DeviceToken"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LcgNodeResponseV2>("/2/device/assignLCG", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeviceGetLiveControlGatewayV2", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
