/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// BulkUserShareShockersUpdateRequest
    /// </summary>
    [DataContract(Name = "BulkUserShareShockersUpdateRequest")]
    public partial class BulkUserShareShockersUpdateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkUserShareShockersUpdateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkUserShareShockersUpdateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkUserShareShockersUpdateRequest" /> class.
        /// </summary>
        /// <param name="permissions">permissions (required).</param>
        /// <param name="limits">limits (required).</param>
        /// <param name="shockers">shockers (required).</param>
        public BulkUserShareShockersUpdateRequest(ShockerPermissions permissions = default, ShockerLimits limits = default, List<Guid> shockers = default)
        {
            // to ensure "permissions" is required (not null)
            if (permissions == null)
            {
                throw new ArgumentNullException("permissions is a required property for BulkUserShareShockersUpdateRequest and cannot be null");
            }
            this.Permissions = permissions;
            // to ensure "limits" is required (not null)
            if (limits == null)
            {
                throw new ArgumentNullException("limits is a required property for BulkUserShareShockersUpdateRequest and cannot be null");
            }
            this.Limits = limits;
            // to ensure "shockers" is required (not null)
            if (shockers == null)
            {
                throw new ArgumentNullException("shockers is a required property for BulkUserShareShockersUpdateRequest and cannot be null");
            }
            this.Shockers = shockers;
        }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name = "permissions", IsRequired = true, EmitDefaultValue = true)]
        public ShockerPermissions Permissions { get; set; }

        /// <summary>
        /// Gets or Sets Limits
        /// </summary>
        [DataMember(Name = "limits", IsRequired = true, EmitDefaultValue = true)]
        public ShockerLimits Limits { get; set; }

        /// <summary>
        /// Gets or Sets Shockers
        /// </summary>
        [DataMember(Name = "shockers", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> Shockers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkUserShareShockersUpdateRequest {\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  Shockers: ").Append(Shockers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
