/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// LoginV2
    /// </summary>
    [DataContract(Name = "LoginV2")]
    public partial class LoginV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginV2" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LoginV2() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginV2" /> class.
        /// </summary>
        /// <param name="password">password (required).</param>
        /// <param name="usernameOrEmail">usernameOrEmail (required).</param>
        /// <param name="turnstileResponse">turnstileResponse (required).</param>
        public LoginV2(string password = default, string usernameOrEmail = default, string turnstileResponse = default)
        {
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for LoginV2 and cannot be null");
            }
            this.Password = password;
            // to ensure "usernameOrEmail" is required (not null)
            if (usernameOrEmail == null)
            {
                throw new ArgumentNullException("usernameOrEmail is a required property for LoginV2 and cannot be null");
            }
            this.UsernameOrEmail = usernameOrEmail;
            // to ensure "turnstileResponse" is required (not null)
            if (turnstileResponse == null)
            {
                throw new ArgumentNullException("turnstileResponse is a required property for LoginV2 and cannot be null");
            }
            this.TurnstileResponse = turnstileResponse;
        }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets UsernameOrEmail
        /// </summary>
        [DataMember(Name = "usernameOrEmail", IsRequired = true, EmitDefaultValue = true)]
        public string UsernameOrEmail { get; set; }

        /// <summary>
        /// Gets or Sets TurnstileResponse
        /// </summary>
        [DataMember(Name = "turnstileResponse", IsRequired = true, EmitDefaultValue = true)]
        public string TurnstileResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginV2 {\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  UsernameOrEmail: ").Append(UsernameOrEmail).Append("\n");
            sb.Append("  TurnstileResponse: ").Append(TurnstileResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 1.", new [] { "Password" });
            }

            // UsernameOrEmail (string) minLength
            if (this.UsernameOrEmail != null && this.UsernameOrEmail.Length < 1)
            {
                yield return new ValidationResult("Invalid value for UsernameOrEmail, length must be greater than 1.", new [] { "UsernameOrEmail" });
            }

            // TurnstileResponse (string) maxLength
            if (this.TurnstileResponse != null && this.TurnstileResponse.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for TurnstileResponse, length must be less than 2048.", new [] { "TurnstileResponse" });
            }

            // TurnstileResponse (string) minLength
            if (this.TurnstileResponse != null && this.TurnstileResponse.Length < 0)
            {
                yield return new ValidationResult("Invalid value for TurnstileResponse, length must be greater than 0.", new [] { "TurnstileResponse" });
            }

            yield break;
        }
    }

}
