/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// SignUpV2
    /// </summary>
    [DataContract(Name = "SignUpV2")]
    public partial class SignUpV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpV2" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignUpV2() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpV2" /> class.
        /// </summary>
        /// <param name="username">username (required).</param>
        /// <param name="password">password (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="turnstileResponse">turnstileResponse (required).</param>
        public SignUpV2(string username = default, string password = default, string email = default, string turnstileResponse = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for SignUpV2 and cannot be null");
            }
            this.Username = username;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for SignUpV2 and cannot be null");
            }
            this.Password = password;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for SignUpV2 and cannot be null");
            }
            this.Email = email;
            // to ensure "turnstileResponse" is required (not null)
            if (turnstileResponse == null)
            {
                throw new ArgumentNullException("turnstileResponse is a required property for SignUpV2 and cannot be null");
            }
            this.TurnstileResponse = turnstileResponse;
        }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        /*
        <example>String</example>
        */
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        /*
        <example>user@example.com</example>
        */
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /*
        <example>user@example.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets TurnstileResponse
        /// </summary>
        [DataMember(Name = "turnstileResponse", IsRequired = true, EmitDefaultValue = true)]
        public string TurnstileResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignUpV2 {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  TurnstileResponse: ").Append(TurnstileResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TurnstileResponse (string) maxLength
            if (this.TurnstileResponse != null && this.TurnstileResponse.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for TurnstileResponse, length must be less than 2048.", new [] { "TurnstileResponse" });
            }

            // TurnstileResponse (string) minLength
            if (this.TurnstileResponse != null && this.TurnstileResponse.Length < 0)
            {
                yield return new ValidationResult("Invalid value for TurnstileResponse, length must be greater than 0.", new [] { "TurnstileResponse" });
            }

            yield break;
        }
    }

}
