/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// V2UserShares
    /// </summary>
    [DataContract(Name = "V2UserShares")]
    public partial class V2UserShares : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V2UserShares" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V2UserShares() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V2UserShares" /> class.
        /// </summary>
        /// <param name="outgoing">outgoing (required).</param>
        /// <param name="incoming">incoming (required).</param>
        public V2UserShares(List<V2UserSharesListItem> outgoing = default, List<V2UserSharesListItem> incoming = default)
        {
            // to ensure "outgoing" is required (not null)
            if (outgoing == null)
            {
                throw new ArgumentNullException("outgoing is a required property for V2UserShares and cannot be null");
            }
            this.Outgoing = outgoing;
            // to ensure "incoming" is required (not null)
            if (incoming == null)
            {
                throw new ArgumentNullException("incoming is a required property for V2UserShares and cannot be null");
            }
            this.Incoming = incoming;
        }

        /// <summary>
        /// Gets or Sets Outgoing
        /// </summary>
        [DataMember(Name = "outgoing", IsRequired = true, EmitDefaultValue = true)]
        public List<V2UserSharesListItem> Outgoing { get; set; }

        /// <summary>
        /// Gets or Sets Incoming
        /// </summary>
        [DataMember(Name = "incoming", IsRequired = true, EmitDefaultValue = true)]
        public List<V2UserSharesListItem> Incoming { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V2UserShares {\n");
            sb.Append("  Outgoing: ").Append(Outgoing).Append("\n");
            sb.Append("  Incoming: ").Append(Incoming).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
