/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CShocker.GeneratedClients.OpenShockClientv1.Client;
using CShocker.GeneratedClients.OpenShockClientv1.Model;

namespace CShocker.GeneratedClients.OpenShockClientv1.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShockerSharesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a share code
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        LegacyEmptyResponse SharesDeleteShareCode(Guid shareCodeId);

        /// <summary>
        /// Delete a share code
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        ApiResponse<LegacyEmptyResponse> SharesDeleteShareCodeWithHttpInfo(Guid shareCodeId);
        /// <summary>
        /// Link a share code to your account
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        LegacyEmptyResponse SharesLinkShareCode(Guid shareCodeId);

        /// <summary>
        /// Link a share code to your account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        ApiResponse<LegacyEmptyResponse> SharesLinkShareCodeWithHttpInfo(Guid shareCodeId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShockerSharesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete a share code
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        System.Threading.Tasks.Task<LegacyEmptyResponse> SharesDeleteShareCodeAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete a share code
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LegacyEmptyResponse>> SharesDeleteShareCodeWithHttpInfoAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Link a share code to your account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        System.Threading.Tasks.Task<LegacyEmptyResponse> SharesLinkShareCodeAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Link a share code to your account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LegacyEmptyResponse>> SharesLinkShareCodeWithHttpInfoAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShockerSharesApi : IShockerSharesApiSync, IShockerSharesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ShockerSharesApi : IDisposable, IShockerSharesApi
    {
        private CShocker.GeneratedClients.OpenShockClientv1.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ShockerSharesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ShockerSharesApi(string basePath)
        {
            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ShockerSharesApi(CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ShockerSharesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ShockerSharesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                new CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ShockerSharesApi(HttpClient client, CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.MergeConfigurations(
                CShocker.GeneratedClients.OpenShockClientv1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerSharesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ShockerSharesApi(CShocker.GeneratedClients.OpenShockClientv1.Client.ISynchronousClient client, CShocker.GeneratedClients.OpenShockClientv1.Client.IAsynchronousClient asyncClient, CShocker.GeneratedClients.OpenShockClientv1.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CShocker.GeneratedClients.OpenShockClientv1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete a share code 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        public LegacyEmptyResponse SharesDeleteShareCode(Guid shareCodeId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = SharesDeleteShareCodeWithHttpInfo(shareCodeId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a share code 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> SharesDeleteShareCodeWithHttpInfo(Guid shareCodeId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("shareCodeId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shareCodeId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<LegacyEmptyResponse>("/1/shares/code/{shareCodeId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SharesDeleteShareCode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a share code 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        public async System.Threading.Tasks.Task<LegacyEmptyResponse> SharesDeleteShareCodeAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = await SharesDeleteShareCodeWithHttpInfoAsync(shareCodeId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a share code 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse>> SharesDeleteShareCodeWithHttpInfoAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("shareCodeId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shareCodeId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<LegacyEmptyResponse>("/1/shares/code/{shareCodeId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SharesDeleteShareCode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Link a share code to your account 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>LegacyEmptyResponse</returns>
        public LegacyEmptyResponse SharesLinkShareCode(Guid shareCodeId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = SharesLinkShareCodeWithHttpInfo(shareCodeId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Link a share code to your account 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <returns>ApiResponse of LegacyEmptyResponse</returns>
        public CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> SharesLinkShareCodeWithHttpInfo(Guid shareCodeId)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("shareCodeId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shareCodeId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LegacyEmptyResponse>("/1/shares/code/{shareCodeId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SharesLinkShareCode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Link a share code to your account 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LegacyEmptyResponse</returns>
        public async System.Threading.Tasks.Task<LegacyEmptyResponse> SharesLinkShareCodeAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default)
        {
            CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse> localVarResponse = await SharesLinkShareCodeWithHttpInfoAsync(shareCodeId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Link a share code to your account 
        /// </summary>
        /// <exception cref="CShocker.GeneratedClients.OpenShockClientv1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="shareCodeId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LegacyEmptyResponse)</returns>
        public async System.Threading.Tasks.Task<CShocker.GeneratedClients.OpenShockClientv1.Client.ApiResponse<LegacyEmptyResponse>> SharesLinkShareCodeWithHttpInfoAsync(Guid shareCodeId, System.Threading.CancellationToken cancellationToken = default)
        {

            CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions localVarRequestOptions = new CShocker.GeneratedClients.OpenShockClientv1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("shareCodeId", CShocker.GeneratedClients.OpenShockClientv1.Client.ClientUtils.ParameterToString(shareCodeId)); // path parameter

            // authentication (UserSessionCookie) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("openShockSession")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("openShockSession", this.Configuration.GetApiKeyWithPrefix("openShockSession")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LegacyEmptyResponse>("/1/shares/code/{shareCodeId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SharesLinkShareCode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
