/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// LoginV2OkResponse
    /// </summary>
    [DataContract(Name = "LoginV2OkResponse")]
    public partial class LoginV2OkResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginV2OkResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LoginV2OkResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginV2OkResponse" /> class.
        /// </summary>
        /// <param name="accountId">accountId (required).</param>
        /// <param name="accountName">accountName (required).</param>
        /// <param name="accountEmail">accountEmail (required).</param>
        /// <param name="isVerified">isVerified (required).</param>
        /// <param name="profileImage">profileImage (required).</param>
        /// <param name="accountRoles">accountRoles (required).</param>
        public LoginV2OkResponse(Guid accountId = default, string accountName = default, string accountEmail = default, bool isVerified = default, string profileImage = default, List<RoleType> accountRoles = default)
        {
            this.AccountId = accountId;
            // to ensure "accountName" is required (not null)
            if (accountName == null)
            {
                throw new ArgumentNullException("accountName is a required property for LoginV2OkResponse and cannot be null");
            }
            this.AccountName = accountName;
            // to ensure "accountEmail" is required (not null)
            if (accountEmail == null)
            {
                throw new ArgumentNullException("accountEmail is a required property for LoginV2OkResponse and cannot be null");
            }
            this.AccountEmail = accountEmail;
            this.IsVerified = isVerified;
            // to ensure "profileImage" is required (not null)
            if (profileImage == null)
            {
                throw new ArgumentNullException("profileImage is a required property for LoginV2OkResponse and cannot be null");
            }
            this.ProfileImage = profileImage;
            // to ensure "accountRoles" is required (not null)
            if (accountRoles == null)
            {
                throw new ArgumentNullException("accountRoles is a required property for LoginV2OkResponse and cannot be null");
            }
            this.AccountRoles = accountRoles;
        }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public Guid AccountId { get; set; }

        /// <summary>
        /// Gets or Sets AccountName
        /// </summary>
        [DataMember(Name = "accountName", IsRequired = true, EmitDefaultValue = true)]
        public string AccountName { get; set; }

        /// <summary>
        /// Gets or Sets AccountEmail
        /// </summary>
        [DataMember(Name = "accountEmail", IsRequired = true, EmitDefaultValue = true)]
        public string AccountEmail { get; set; }

        /// <summary>
        /// Gets or Sets IsVerified
        /// </summary>
        [DataMember(Name = "isVerified", IsRequired = true, EmitDefaultValue = true)]
        public bool IsVerified { get; set; }

        /// <summary>
        /// Gets or Sets ProfileImage
        /// </summary>
        [DataMember(Name = "profileImage", IsRequired = true, EmitDefaultValue = true)]
        public string ProfileImage { get; set; }

        /// <summary>
        /// Gets or Sets AccountRoles
        /// </summary>
        [DataMember(Name = "accountRoles", IsRequired = true, EmitDefaultValue = true)]
        public List<RoleType> AccountRoles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginV2OkResponse {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AccountName: ").Append(AccountName).Append("\n");
            sb.Append("  AccountEmail: ").Append(AccountEmail).Append("\n");
            sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
            sb.Append("  ProfileImage: ").Append(ProfileImage).Append("\n");
            sb.Append("  AccountRoles: ").Append(AccountRoles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
