/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// Defines RoleType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RoleType
    {
        /// <summary>
        /// Enum Support for value: Support
        /// </summary>
        [EnumMember(Value = "Support")]
        Support = 1,

        /// <summary>
        /// Enum Staff for value: Staff
        /// </summary>
        [EnumMember(Value = "Staff")]
        Staff = 2,

        /// <summary>
        /// Enum Admin for value: Admin
        /// </summary>
        [EnumMember(Value = "Admin")]
        Admin = 3,

        /// <summary>
        /// Enum System for value: System
        /// </summary>
        [EnumMember(Value = "System")]
        System = 4
    }

}
