/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// ShareInviteBaseDetails
    /// </summary>
    [DataContract(Name = "ShareInviteBaseDetails")]
    public partial class ShareInviteBaseDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareInviteBaseDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShareInviteBaseDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareInviteBaseDetails" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="owner">owner (required).</param>
        /// <param name="sharedWith">sharedWith (required).</param>
        /// <param name="shockers">shockers (required).</param>
        public ShareInviteBaseDetails(Guid id = default, DateTime createdAt = default, BasicUserInfo owner = default, BasicUserInfo sharedWith = default, List<ShockerPermLimitPairWithIdAndName> shockers = default)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            // to ensure "owner" is required (not null)
            if (owner == null)
            {
                throw new ArgumentNullException("owner is a required property for ShareInviteBaseDetails and cannot be null");
            }
            this.Owner = owner;
            // to ensure "sharedWith" is required (not null)
            if (sharedWith == null)
            {
                throw new ArgumentNullException("sharedWith is a required property for ShareInviteBaseDetails and cannot be null");
            }
            this.SharedWith = sharedWith;
            // to ensure "shockers" is required (not null)
            if (shockers == null)
            {
                throw new ArgumentNullException("shockers is a required property for ShareInviteBaseDetails and cannot be null");
            }
            this.Shockers = shockers;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [DataMember(Name = "owner", IsRequired = true, EmitDefaultValue = true)]
        public BasicUserInfo Owner { get; set; }

        /// <summary>
        /// Gets or Sets SharedWith
        /// </summary>
        [DataMember(Name = "sharedWith", IsRequired = true, EmitDefaultValue = true)]
        public BasicUserInfo SharedWith { get; set; }

        /// <summary>
        /// Gets or Sets Shockers
        /// </summary>
        [DataMember(Name = "shockers", IsRequired = true, EmitDefaultValue = true)]
        public List<ShockerPermLimitPairWithIdAndName> Shockers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShareInviteBaseDetails {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  SharedWith: ").Append(SharedWith).Append("\n");
            sb.Append("  Shockers: ").Append(Shockers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
