/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// ShockerPermLimitPairWithIdAndName
    /// </summary>
    [DataContract(Name = "ShockerPermLimitPairWithIdAndName")]
    public partial class ShockerPermLimitPairWithIdAndName : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerPermLimitPairWithIdAndName" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShockerPermLimitPairWithIdAndName() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShockerPermLimitPairWithIdAndName" /> class.
        /// </summary>
        /// <param name="permissions">permissions (required).</param>
        /// <param name="limits">limits (required).</param>
        /// <param name="id">id.</param>
        /// <param name="name">name (required).</param>
        public ShockerPermLimitPairWithIdAndName(ShockerPermissions permissions = default, ShockerLimits limits = default, Guid id = default, string name = default)
        {
            // to ensure "permissions" is required (not null)
            if (permissions == null)
            {
                throw new ArgumentNullException("permissions is a required property for ShockerPermLimitPairWithIdAndName and cannot be null");
            }
            this.Permissions = permissions;
            // to ensure "limits" is required (not null)
            if (limits == null)
            {
                throw new ArgumentNullException("limits is a required property for ShockerPermLimitPairWithIdAndName and cannot be null");
            }
            this.Limits = limits;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ShockerPermLimitPairWithIdAndName and cannot be null");
            }
            this.Name = name;
            this.Id = id;
        }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name = "permissions", IsRequired = true, EmitDefaultValue = true)]
        public ShockerPermissions Permissions { get; set; }

        /// <summary>
        /// Gets or Sets Limits
        /// </summary>
        [DataMember(Name = "limits", IsRequired = true, EmitDefaultValue = true)]
        public ShockerLimits Limits { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShockerPermLimitPairWithIdAndName {\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
