/*
 * OpenShock.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CShocker.GeneratedClients.OpenShockClient.Client.FileParameter;
using OpenAPIDateConverter = CShocker.GeneratedClients.OpenShockClient.Client.OpenAPIDateConverter;

namespace CShocker.GeneratedClients.OpenShockClient.Model
{
    /// <summary>
    /// UsernameCheckResponse
    /// </summary>
    [DataContract(Name = "UsernameCheckResponse")]
    public partial class UsernameCheckResponse : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Availability
        /// </summary>
        [DataMember(Name = "availability", IsRequired = true, EmitDefaultValue = true)]
        public UsernameAvailability Availability { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UsernameCheckResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UsernameCheckResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UsernameCheckResponse" /> class.
        /// </summary>
        /// <param name="availability">availability (required).</param>
        /// <param name="error">error.</param>
        public UsernameCheckResponse(UsernameAvailability availability = default, UsernameError error = default)
        {
            this.Availability = availability;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public UsernameError Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsernameCheckResponse {\n");
            sb.Append("  Availability: ").Append(Availability).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
